# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('description', models.TextField(verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
            ],
            options={
                'verbose_name': 'static page',
                'verbose_name_plural': 'static pages',
            },
        ),
    ]
